### ISSUE TITLE
Action fails when version already exists

### ISSUE THREAD

**Issue by MoazHussam** [sadiq81/fastlane-plugin-jira_set_fix_version#1]
The action fails when a Jira version already exists.

### Steps

1.  Go to the Jira website and create a new version
1.  Run the ```jira_set_fix_version``` action

### Expected results

The Jira version should be updated with the included Jira issues found in the commit changelog

### Acual results

The action fails and returns Jira error.

### Importance

This is really important because setting a Jira fix version for an existing version is very common and the action should handle this.

### Example

```ruby
changelog_from_git_commits(
merge_commit_filtering: 'only_include_merges',
commits_count: 1,
pretty: '%b',
match_lightweight_tag: false
)
jira_set_fix_version(
project_name: project_code,
name: '3.10',
url: 'URL',
username: 'USERNAME',
password: 'PASSWORD'
)
```

The log from the terminal:

```
[10:19:01]: JIRA::HTTPError

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | default_platform           | 0           |
| 2    | changelog_from_git_commits | 0           |
| 💥   | jira_set_fix_version       | 2           |
+------+----------------------------+-------------+

[10:19:01]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Suggestion for new action
    https://github.com/fastlane/fastlane/issues/11644 [closed] 5 💬
    23 Mar 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        30: from /usr/local/bin/fastlane:23:in `<main>'
        29: from /usr/local/bin/fastlane:23:in `load'
        28: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
        27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        26: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        24: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        22: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        21: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        20: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        12: from Fastfile:224:in `block (2 levels) in parsing_binding'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels)in execute_action'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-jira_set_fix_version-1.0.0/lib/fastlane/plugin/jira_set_fix_version/actions/jira_set_fix_version_action.rb:47:in `run'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/jira-ruby-1.5.0/lib/jira/base.rb:351:in `save!'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/jira-ruby-1.5.0/lib/jira/client.rb:216:in `post'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/jira-ruby-1.5.0/lib/jira/client.rb:228:in `request'
/usr/local/lib/ruby/gems/2.5.0/gems/jira-ruby-1.5.0/lib/jira/request_client.rb:16:in `request': Bad Request (JIRA::HTTPError)
```

**Comment by MoazHussam** [comment]
I've created pull request #2 to fix this issue

**Comment by jimenezjc83** [comment]
@sadiq81 @MoazHussam This issue is still happening. Above is the PR with some small fixes.
